# Generated by Django 5.0.6 on 2024-05-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='customer',
        ),
    ]
