# Generated by Django 5.0.6 on 2024-05-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_product',
            new_name='products',
        ),
    ]
